name: FTP Deploy

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch (adjust if necessary)

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ftp.battiwestzeo.lk
          username: ${{ secrets.SMGT_USERNAME }}
          password: ${{ secrets.SMGT_PASSWORD }}
          local-dir: ./
          server-dir: ./
          exclude: |
            public/index.php
            public/*
            storage/*
            vendor/*